### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663

### ISSUE THREAD

**Issue by GuoLanqing** [csjunxu/Noisy-As-Clean#1]
After I install the env, it prompts out the error as below. Hope for your kind help. Thanks.
```
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663
```

**Comment by csjunxu** [comment]
maybe the error is the version of cuda, I did not meet this error before.

**Comment by Yueziyu** [comment]
我也出现了这个问题，能麻烦问一下你们的cuda版本是什么吗？我这边的环境是titanRTX，cuda10.1，配置其他程序的环境目前没发现问题。

**Comment by Yueziyu** [comment]
> After I install the env, it prompts out the error as below. Hope for your kind help. Thanks.
> 
> ```
> RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663
> ```
You can make torch.backends.cudnn.benchmark = False from True to solve thie problem, but there also has other problem in this code.

**Comment by csjunxu** [comment]
It is resolved?
