### ISSUE TITLE
train nac_resnet_set12.py时，psnr_2 = compare_psnr(img_aug_np[0].transpose(1, 2, 0), np.clip(final_reuslt, 0, 1))出现维度不一致问题

### ISSUE THREAD

**Issue by Yueziyu** [csjunxu/Noisy-As-Clean#2]
在运行train nac_resnet_set12.py时，在代码

>psnr_2 = compare_psnr(img_aug_np[0].transpose(1, 2, 0), np.clip(final_reuslt, 0, 1))报错二者维度不一致，检查后发现final_reuslt是一个(512,512,512)的数组，前者则是(512,512,1)，这个是前面代码中变量out_effect_np导致的，这个list len是8，前4个元素维度是(512,512,1)，后四个是(1,512,512)，请问这里的问题怎么解决？

**Comment by csjunxu** [comment]
The reason is the you loss the final loss function?

As described by the email you sent me recently. So This problem is resolved.
